// examples/showcase.vue
<template>
  <!-- Vue Template: Tags #39C5BB Bold, Attributes #4DD0E1 Italic -->
  <div class="miku-stage" :class="{ performing: isPerforming }">
    <!-- Component Tag: #B2EBE7 Bold (Ice Teal) -->
    <MikuHeader :title="title" @click="handleClick" />

    <!-- Vue Directives: #39C5BB Bold -->
    <section v-if="isReady">
      <h1>{{ title }}</h1>

      <!-- v-for Directive -->
      <ul class="voice-list">
        <li
          v-for="(voice, index) in voiceBanks"
          :key="voice.id"
          :data-index="index"
        >
          <!-- Interpolation: #4DD0E1 -->
          {{ voice.name }} - {{ voice.version }}
        </li>
      </ul>

      <!-- v-model Directive -->
      <input
        v-model="searchQuery"
        type="text"
        placeholder="Search voices..."
        @input="onSearch"
      />

      <!-- v-show Directive -->
      <p v-show="voiceBanks.length === 0">No voices found</p>

      <!-- Event Modifiers -->
      <button
        @click.prevent.stop="startPerformance"
        :disabled="!canPerform"
      >
        Start Performance
      </button>
    </section>

    <!-- v-else Directive -->
    <LoadingSpinner v-else />

    <!-- Slot -->
    <slot name="footer">
      <DefaultFooter />
    </slot>
  </div>
</template>

<script setup lang="ts">
/**
 * Hatsune Miku Theme - Vue 3 Showcase
 * All-Miku Synthesis: Every voice, one stage.
 */

import { ref, computed, watch, onMounted, defineProps, defineEmits } from 'vue'
import type { VoiceBank, MikuVersion } from '@/types'

// Component imports: #B2EBE7 Bold
import MikuHeader from './MikuHeader.vue'
import LoadingSpinner from './LoadingSpinner.vue'
import DefaultFooter from './DefaultFooter.vue'

// Props: defineProps
interface Props {
  initialVoice?: VoiceBank
  version?: MikuVersion
}

const props = withDefaults(defineProps<Props>(), {
  version: 'V2'
})

// Emits: defineEmits
const emit = defineEmits<{
  (e: 'perform', song: string): void
  (e: 'change', voice: VoiceBank): void
}>()

// Refs: #C8DCD9 (Variables)
const title = ref<string>('Hatsune Miku Stage')
const isReady = ref<boolean>(false)
const isPerforming = ref<boolean>(false)
const searchQuery = ref<string>('')
const voiceBanks = ref<VoiceBank[]>([])

// Constants: #E05096 (Magenta)
const CANONICAL_COLOR = '#39C5BB' as const
const DEFAULT_BPM = 39

// Computed: #00BCD4 (Functions)
const canPerform = computed(() => {
  return isReady.value && voiceBanks.value.length > 0
})

const filteredVoices = computed(() => {
  const query = searchQuery.value.toLowerCase()
  return voiceBanks.value.filter(voice =>
    voice.name.toLowerCase().includes(query)
  )
})

// Methods: #00BCD4
function handleClick(event: MouseEvent): void {
  console.log('Clicked:', event.target)
}

function onSearch(): void {
  console.log('Searching:', searchQuery.value)
}

async function startPerformance(): Promise<void> {
  isPerforming.value = true

  try {
    await new Promise(resolve => setTimeout(resolve, 1000))
    emit('perform', 'World is Mine')
  } finally {
    isPerforming.value = false
  }
}

// Watch: #00BCD4
watch(searchQuery, (newValue, oldValue) => {
  console.log(`Search changed: ${oldValue} -> ${newValue}`)
})

watch(
  () => props.version,
  (newVersion) => {
    console.log('Version changed:', newVersion)
  },
  { immediate: true }
)

// Lifecycle: #00BCD4
onMounted(async () => {
  // Fetch voice banks
  const response = await fetch('/api/voices')
  voiceBanks.value = await response.json()
  isReady.value = true
})
</script>

<style scoped>
/* Scoped CSS */
.miku-stage {
  /* CSS Variable: #4DD0E1 */
  --primary-color: v-bind(CANONICAL_COLOR);

  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 2rem;
  background: #1a1f24;
}

/* Class Selector: #39C5BB */
.voice-list {
  list-style: none;
  padding: 0;
}

.voice-list li {
  padding: 0.5rem;
  border-left: 3px solid var(--primary-color);
  margin-bottom: 0.5rem;
}

/* State Class */
.performing {
  animation: pulse 1s ease-in-out infinite;
}

/* Keyframes: @keyword #E05096 */
@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.7; }
}
</style>

// examples/showcase.svelte
<script lang="ts">
  /**
   * Hatsune Miku Theme - Svelte Showcase
   * All-Miku Synthesis: Every voice, one stage.
   */

  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import { writable, derived, type Writable } from 'svelte/store'

  // Types: #B2EBE7 Bold (Ice Teal)
  interface VoiceBank {
    id: string
    name: string
    version: 'V2' | 'V3' | 'V4X' | 'NT' | 'SEKAI'
  }

  type AppendType = 'dark' | 'soft' | 'light' | 'sweet' | 'vivid' | 'solid'

  // Props
  export let title: string = 'Hatsune Miku Stage'
  export let initialVoices: VoiceBank[] = []

  // Constants: #E05096 (Magenta)
  const CANONICAL_COLOR = '#39C5BB'
  const DEFAULT_BPM = 39

  // Event dispatcher
  const dispatch = createEventDispatcher<{
    perform: { song: string; bpm: number }
    select: VoiceBank
  }>()

  // Stores: Writable<T>
  const voices: Writable<VoiceBank[]> = writable(initialVoices)
  const searchQuery = writable('')
  const isPerforming = writable(false)

  // Derived store: #00BCD4 (Functions)
  const filteredVoices = derived(
    [voices, searchQuery],
    ([$voices, $query]) => {
      if (!$query) return $voices
      return $voices.filter(v =>
        v.name.toLowerCase().includes($query.toLowerCase())
      )
    }
  )

  // Reactive declarations: $: syntax
  $: voiceCount = $voices.length
  $: hasVoices = voiceCount > 0
  $: statusMessage = $isPerforming ? 'Performing...' : 'Ready'

  // Functions: #00BCD4 (NT Cyan)
  function handleSearch(event: Event): void {
    const target = event.target as HTMLInputElement
    searchQuery.set(target.value)
  }

  async function startPerformance(song: string): Promise<void> {
    isPerforming.set(true)

    try {
      await new Promise(resolve => setTimeout(resolve, 2000))
      dispatch('perform', { song, bpm: DEFAULT_BPM })
    } finally {
      isPerforming.set(false)
    }
  }

  function selectVoice(voice: VoiceBank): void {
    dispatch('select', voice)
  }

  // Lifecycle: #00BCD4
  onMount(async () => {
    console.log('Component mounted')

    // Fetch initial data
    const response = await fetch('/api/voices')
    const data = await response.json()
    voices.set(data)
  })

  onDestroy(() => {
    console.log('Component destroyed')
  })
</script>

<!-- Svelte Template -->
<div class="miku-stage" class:performing={$isPerforming}>
  <!-- HTML Tag: #39C5BB Bold -->
  <header>
    <h1>{title}</h1>
    <span class="status">{statusMessage}</span>
  </header>

  <!-- Svelte Block: {#if} - #39C5BB Bold -->
  {#if hasVoices}
    <section class="controls">
      <!-- Two-way binding: bind: -->
      <input
        type="text"
        placeholder="Search voices..."
        bind:value={$searchQuery}
        on:input={handleSearch}
      />
    </section>

    <!-- Svelte Block: {#each} -->
    <ul class="voice-list">
      {#each $filteredVoices as voice, index (voice.id)}
        <li
          class="voice-item"
          class:selected={index === 0}
          on:click={() => selectVoice(voice)}
          on:keydown={(e) => e.key === 'Enter' && selectVoice(voice)}
          role="button"
          tabindex="0"
        >
          <!-- Expression: {expression} -->
          <span class="name">{voice.name}</span>
          <span class="version">{voice.version}</span>
        </li>
      {:else}
        <!-- Empty state -->
        <li class="empty">No voices match your search</li>
      {/each}
    </ul>

    <!-- Event with modifiers -->
    <button
      on:click|preventDefault|stopPropagation={() => startPerformance('World is Mine')}
      disabled={$isPerforming}
    >
      {$isPerforming ? 'Performing...' : 'Start Performance'}
    </button>
  {:else}
    <!-- Svelte Block: {:else} -->
    <p class="loading">Loading voices...</p>
  {/if}

  <!-- Svelte Block: {#await} -->
  {#await fetch('/api/status')}
    <p>Checking status...</p>
  {:then response}
    <p>Status: {response.status}</p>
  {:catch error}
    <p class="error">Error: {error.message}</p>
  {/await}

  <!-- Slot -->
  <slot name="footer">
    <footer>
      <p>Canonical Color: {CANONICAL_COLOR}</p>
    </footer>
  </slot>
</div>

<style>
  /* CSS in Svelte */
  .miku-stage {
    --primary: #39c5bb;
    --secondary: #00bcd4;

    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 2rem;
    background: #1a1f24;
    color: #c8dcd9;
  }

  /* Class: #39C5BB */
  .voice-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .voice-item {
    display: flex;
    justify-content: space-between;
    padding: 0.75rem;
    border-left: 3px solid var(--primary);
    margin-bottom: 0.5rem;
    cursor: pointer;
    transition: background 150ms ease;
  }

  .voice-item:hover {
    background: rgba(57, 197, 187, 0.1);
  }

  /* Conditional class */
  .voice-item.selected {
    background: rgba(57, 197, 187, 0.2);
    border-color: var(--secondary);
  }

  .performing {
    opacity: 0.8;
    pointer-events: none;
  }

  .error {
    color: #ff5370;
  }

  /* Animation */
  @keyframes fade-in {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  .voice-item {
    animation: fade-in 300ms ease;
  }
</style>
